export const REQUIRED_ERR = 'This field is required';
export const NAME_MIN_VALLATION_ERR = 'Name must be minimum 2 character';
export const NAME_MAX_VALIDATION_ERR = 'Name be greater than 20 character!';
export const FIRST_NAME_MIN_VALIDATION_ERR = 'First Name must be minimum 2 character';
export const FIRST_NAME_MAX_VALIDATION_ERR = 'First Name not be greater than 20 character!';
export const LAST_NAME_MIN_VALIDATION_ERR = 'Last Name must be minimum 2 character';
export const LAST_NAME_MAX_VALIDATION_ERR = 'Last Name not be greater than 20 character';
export const COMPANY_NAME_MIN_VALIDATION_ERR = 'Company Name must be minimum 4 character';
export const COMPANY_NAME_MAX_VALIDATION_ERR = 'Company Name not be greater than 20 character';
export const EMAIL_VALLATION_ERR = 'Email must be valid';
export const PASSWORD_REGEXP = /^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,32}$/;
export const PASSWORD_VALIDATION_ERR =
  'At least 8 characters, max 32 characters,  one uppercase letter, one lowercase letter, one number and one special case character';
export const CONFIRM_PASSWORD_ERR = 'Confirm password does not match with password';
export const TERMS_COND_ERR = 'Please accept terms and condition';
export const COOKIE_POLICY_ERR = 'Please accept cookie terms and condition';
export const PRIVACY_POLICY_ERR = 'Please accept  privacy policy';
export const FINANCIAL_POLICY_ERR = 'Please accept financial services T&Cs and privacy policy';
export const MOBILE_NO_ERR =  /^\d{10}$/;
export const OTP_MAX_VALIDATION_ERR = 'Otp must be 4 character!';
